

// CONFIGURACIÓN PARA TU ESTRUCTURA DE CARPETAS
const DRIVE_CONFIG = {
    // CARPETA PRINCIPAL QUE CONTIENE LA SUBCARPETA QUECHUA
    CARPETA_EDUCAWAYRA: "1DcCLUfgMqL8NzXXjkI6aoJLlPMSNwmQY",
    
    // SUB-CARPETA QUECHUA DENTRO DE EDUCAWAYRA
    CARPETA_QUECHUA: "15aDsoMEXfoTHx9jjiTFfAlrqQ1SEGMxf", // ← NECESITAMOS ESTE ID

    CARPETA_CARRUSEL: "1mjOgM47UgxxgsvHIbMatiA98NZNBRzA2",
    CARPETA_FINAL: "144zK9nb0OhG57L6gTUXp-qOj3zrw1yDQ",
    
    // SUB-CARPETAS DENTRO DE QUECHUA
    CARPETA_IMAGENES: "101wU2F5Sjl72hdtlxDBkbMIOEHQFAo-Y", 
    CARPETA_VIDEOS: "1N6AUdU6iOZK1KKsF27SbeQ3DuGKAU68b",
    
    // API KEY PÚBLICA
    API_KEY: "AIzaSyDAANqPDD5qsKXyTht-G-N65p7bV9XCTQ0"
};



