

// CONFIGURACIÓN PARA TU ESTRUCTURA DE CARPETAS
const DRIVE_CONFIG = {
    // CARPETA PRINCIPAL QUE CONTIENE LA SUBCARPETA QUECHUA
    CARPETA_EDUCAWAYRA: "1DcCLUfgMqL8NzXXjkI6aoJLlPMSNwmQY",
    
    // SUB-CARPETA QUECHUA DENTRO DE EDUCAWAYRA
    CARPETA_COAR: "1rn1wKRzP8I-EQzBo-Be2tvMeXHzRnmB4", // ← NECESITAMOS ESTE ID

    CARPETA_CARRUSEL: "1mFqZ-mS-uPgTimmqMd-LIsDzxs80FELe",
    CARPETA_FINAL: "1DyV-t1fvEsy7K7xREytnTkuaNywiO4uZ",
    
    // SUB-CARPETAS DENTRO DE QUECHUA
    CARPETA_IMAGENES: "1kSlhBojt8mMYn5m8cdSJFvp0pE6YWMHT", 
    CARPETA_VIDEOS: "1F_EvJhPspiUOHpgOC2DLpjpZkt6G_HRE",
    
    // API KEY PÚBLICA
    API_KEY: "AIzaSyDAANqPDD5qsKXyTht-G-N65p7bV9XCTQ0"
};



